# documentation: https://n8n.io
# slogan: n8n is an extendable workflow automation tool.
# category: automation
# tags: n8n,workflow,automation,open,source,low,code
# logo: svgs/n8n.png
# port: 5678

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.119.2
    environment:
      - SERVICE_URL_N8N_5678
      - N8N_EDITOR_BASE_URL=${SERVICE_URL_N8N}
      - WEBHOOK_URL=${SERVICE_URL_N8N}
      - N8N_HOST=${SERVICE_URL_N8N}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/Berlin}
      - TZ=${TZ:-Europe/Berlin}
      - DB_SQLITE_POOL_SIZE=${DB_SQLITE_POOL_SIZE:-3}
      - N8N_RUNNERS_ENABLED=${N8N_RUNNERS_ENABLED:-true}
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=${N8N_BLOCK_ENV_ACCESS_IN_NODE:-true}
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=${N8N_GIT_NODE_DISABLE_BARE_REPOS:-true}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS:-true}
      - N8N_PROXY_HOPS=${N8N_PROXY_HOPS:-1}
    volumes:
      - n8n-data:/home/node/.n8n
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:5678/"]
      interval: 5s
      timeout: 20s
      retries: 10
